//@	{"dependencies_extra":[{"ref":"glfw3", "origin":"pkg-config"}]}

#ifndef FRUIT_LIB_GLFWEVENTMAPPER_HPP
#define FRUIT_LIB_GLFWEVENTMAPPER_HPP

#include "./event_dispatcher.hpp"
#include "./location_event.hpp"
#include "./ball_event.hpp"

#define GLFW_INCLUDE_NONE
#include <GLFW/glfw3.h>

namespace fruit
{
	/**
	* \defgroup glfw_event_helpers GLFW event converters
	*
	* \brief Functions to convert GLFW events to fruit Events
	*
	* These functions converts events generated by GLFW into fruit Events. Typically, these are called
	* from a suitable GLFW event callback. The return value is then passed on to a UiManager for
	* further processing.
	*/

	/**
	* \brief Converts a mouse button event (usually caught by a GLFWmousebuttonfun) into a LocationEvent
	*
	* \ingroup glfw_event_helpers
	*/
	inline LocationEvent convert(LocationEvent::MouseButtonTag, GLFWwindow& src, int button, int action)
	{
		double x{};
		double y{};
		glfwGetCursorPos(&src, &x, &y);

		return LocationEvent{
			Point{static_cast<float>(x), static_cast<float>(y), 0.0f},
			action == GLFW_RELEASE? ButtonPressure{ButtonPressure::action_release}:
				ButtonPressure{ButtonPressure::action_press},
			button
		};
	}

	/**
	* \brief Converts a mouse move event (usually caught by a GLFWcursorposfun) into a LocationEvent
	*
	* \ingroup glfw_event_helpers
	*/
	inline LocationEvent convert(LocationEvent::MouseMoveTag, GLFWwindow&, double x, double y)
	{
		return LocationEvent{
			Point{static_cast<float>(x), static_cast<float>(y), 0.0f},
			ButtonPressure{0.0f},
			0};
	}

	/**
	* \brief Converts a scroll event (usually caught by a  GLFWscrollfun) into a BallEvent
	*
	* \ingroup glfw_event_helpers
	*/
	inline BallEvent convert(BallEvent::ScrollTag, GLFWwindow&, double dx, double dy)
	{
		return BallEvent{Vector{static_cast<float>(dx), static_cast<float>(dy), 0.0f}};
	}
}

#endif
